TARGET_CPU="0.25"          # SWAN/thread-hour
TARGET_MEMORY="0.139"       # SWAN/GB-hour
TARGET_HD_EPHEMERAL="0.035" # SWAN/GB-hour
TARGET_GPU_DEFAULT="17.5" # SWAN/Default GPU unit a hour
TARGET_GPU_A100=""   # SWAN/T4 GPU unit a hour

