TARGET_CPU="1.2"          # SWAN/thread-hour
TARGET_MEMORY="1.0"       # SWAN/GB-hour
TARGET_HD_EPHEMERAL="0.06" # SWAN/GB-hour
TARGET_GPU_DEFAULT="5" # SWAN/Default GPU unit a hour
TARGET_GPU_A100=""   # SWAN/T4 GPU unit a hour

