TARGET_CPU=""          # SWAN/thread-hour
TARGET_MEMORY=""       # SWAN/GB-hour
TARGET_HD_EPHEMERAL="" # SWAN/GB-hour
TARGET_GPU_DEFAULT="" # SWAN/Default GPU unit a hour
TARGET_GPU_A100=""   # SWAN/T4 GPU unit a hour

