TARGET_CPU="1.60"          # SWAN/thread-hour
TARGET_MEMORY="0.80"       # SWAN/GB-hour
TARGET_HD_EPHEMERAL="0.02" # SWAN/GB-hour
TARGET_GPU_DEFAULT="400" # SWAN/Default GPU unit a hour
TARGET_GPU_T4="200"   # SWAN/T4 GPU unit a hour
TARGET_GPU_V100="300" # SWAN/V100 GPU unit a hour

