TARGET_CPU="1.60"          # SWAN/thread-hour
TARGET_MEMORY="0.80"       # SWAN/GB-hour
TARGET_HD_EPHEMERAL="0.02" # SWAN/GB-hour
TARGET_GPU_DEFAULT="5" # SWAN/Default GPU unit a hour
TARGET_GPU_A100=""   # SWAN/T4 GPU unit a hour

